blank_issues_enabled: false
contact_links:
  - name: REG-Linux general chanel
    url: https://discord.gg/a9HH4ZpVqp
    about: REG-Linux, emulation and general operating system features
  - name: Help and support
    url: https://discord.gg/JnSyJrXS4G
    about: For support with using REG-Linux

